version: '3.4'
services:

  dispatcher:
    image: dockerhubmg2023/dispatcher:v8
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dispatcher
    restart: unless-stopped
    ports:
      - "3002:3002"
    networks:
        - gcm_subnet

networks:
  gcm_subnet:
    driver: bridge
    name: gcm
    external: true