version: '3.4'
services:

  transporter:
    image: dockerhubmg2023/transporter:v2
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transporter
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
        - gcm_subnet

networks:
  gcm_subnet:
    driver: bridge
    name: gcm
    external: true