version: '3.4'
services:

  collector:
    image: dockerhubmg2023/collector:v8
    build:
      context: .
      dockerfile: Dockerfile
    container_name: collector
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
        - gcm_subnet

networks:
  gcm_subnet:
    driver: bridge
    name: gcm
    external: true